In [104]:
import pandas as pd
from pathlib import Path

players_df = pd.read_csv("../data/processed/fpl/ENG-Premier League/2026-2027/season/cleaned_players.csv", usecols=["name", "fpl_pos", "team", "now_cost", "defcon"])
players_defcon_df = pd.read_csv("../data/processed/fpl/ENG-Premier League/2025-2026/season/cleaned_players.csv", usecols=["name", "minutes", "fpl_pos", "team", "now_cost", "defcon", 'total_points', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded', 'penalties_saved', 'penalties_missed', 'yellow_cards', 'red_cards', 'saves', 'bonus', 'bps'])
pd.set_option("display.max_columns", None)


print(players_defcon_df.dtypes)
print(players_defcon_df[players_defcon_df['penalties_missed'] > 0].head())

goals_scored          int64
assists               int64
total_points          int64
minutes               int64
goals_conceded        int64
bonus                 int64
bps                   int64
clean_sheets          int64
red_cards             int64
yellow_cards          int64
now_cost              int64
name                    str
team                    str
fpl_pos                 str
defcon              float64
saves               float64
penalties_saved     float64
penalties_missed    float64
dtype: object
Empty DataFrame
Columns: [goals_scored, assists, total_points, minutes, goals_conceded, bonus, bps, clean_sheets, red_cards, yellow_cards, now_cost, name, team, fpl_pos, defcon, saves, penalties_saved, penalties_missed]
Index: []

In [98]:
#player prices
#mids
mids_df = players_df[players_df['fpl_pos'].eq('MID')].sort_values("now_cost", ascending=False).reset_index(drop=True)
mids_edges = [0, 50, 60, 75, 90, 200]
mids_labels = ['fodder', 'budget', 'mid-tier', 'top-tier', 'premium']
mids_categories = pd.cut(mids_df['now_cost'], bins=mids_edges, labels=mids_labels, right=False)
mids_df['price_category'] = mids_categories
print(f"Midfielders by custom categories:", mids_categories.value_counts())
display(f"Midfielders Prices:",  mids_df)

#defs
defs_df = players_df[players_df['fpl_pos'].eq('DEF')].sort_values("now_cost", ascending=False).reset_index(drop=True)
defs_edges = [0, 45, 55, 65, 75, 200]
defs_labels = ['fodder', 'budget', 'mid-tier', 'top-tier', 'premium']
defs_categories = pd.cut(defs_df['now_cost'], bins=defs_edges, labels=defs_labels, right=False)
defs_df['price_category'] = defs_categories
print(f"Defenders by custom categories:", defs_categories.value_counts())
defs_df['price_category'] = defs_categories
display(f"Defenders Prices:",  defs_df)

#fwds
fwds_df = players_df[players_df['fpl_pos'].eq('FWD')].sort_values("now_cost", ascending=False).reset_index(drop=True)
fwds_edges = [0, 50, 60, 70, 90, 200]
fwds_labels = ['fodder', 'budget', 'mid-tier', 'top-tier', 'premium']
fwds_categories = pd.cut(fwds_df['now_cost'], bins=fwds_edges, labels=fwds_labels, right=False)
fwds_df['price_category'] = fwds_categories
print(f"Forwards by custom categories:", fwds_categories.value_counts())
fwds_df['price_category'] = fwds_categories
display(f"Forwards Prices:",  fwds_df)

#gks
gks_df = players_df[players_df['fpl_pos'].eq('GKP')].sort_values("now_cost", ascending=False).reset_index(drop=True)
gks_edges = [0, 41, 50, 55, 200]
gks_labels = ['fodder', 'budget', 'mid-tier', 'premium']
gks_categories = pd.cut(gks_df['now_cost'], bins=gks_edges, labels=gks_labels, right=False)
gks_df['price_category'] = gks_categories
print(f"Goalkeepers by custom categories:", gks_categories.value_counts())
gks_df['price_category'] = gks_categories
display(f"Goalkeepers Prices:",  gks_df)

Midfielders by custom categories: now_cost
budget      152
mid-tier     59
fodder       25
top-tier     10
premium       3
Name: count, dtype: int64

'Midfielders Prices:'

     now_cost             name team fpl_pos  defcon price_category
0         120  Bruno Fernandes  MUN     MID     NaN        premium
1          95      Cole Palmer  CHE     MID     NaN        premium
2          95      Bukayo Saka  ARS     MID     NaN        premium
3          85  Antoine Semenyo  MCI     MID     NaN       top-tier
4          80     Bryan Mbeumo  MUN     MID     NaN       top-tier
..        ...              ...  ...     ...     ...            ...
244        45     Regan Slater  HUL     MID     NaN         fodder
245        45  Bendito Mantato  MUN     MID     NaN         fodder
246        45   Tyler Fletcher  MUN     MID     NaN         fodder
247        45       Ryan Yates  NFO     MID     NaN         fodder
248        45   Callum Olusesi  TOT     MID     NaN         fodder

[249 rows x 6 columns]

Defenders by custom categories: now_cost
budget      106
fodder       47
mid-tier     28
top-tier      3
premium       1
Name: count, dtype: int64

'Defenders Prices:'

     now_cost               name team fpl_pos  defcon price_category
0          80  Gabriel Magalhães  ARS     DEF     NaN        premium
1          65     Jurriën Timber  ARS     DEF     NaN       top-tier
2          65    Virgil van Dijk  LIV     DEF     NaN       top-tier
3          65      Nico O’Reilly  MCI     DEF     NaN       top-tier
4          60     William Saliba  ARS     DEF     NaN       mid-tier
..        ...                ...  ...     ...     ...            ...
180        40     Jun'ai Byfield  TOT     DEF     NaN         fodder
181        40     James Rowswell  TOT     DEF     NaN         fodder
182        40    Leo Fuhr Hjelde  SUN     DEF     NaN         fodder
183        40        Luke O'Nien  SUN     DEF     NaN         fodder
184        40     Arthur Masuaku  SUN     DEF     NaN         fodder

[185 rows x 6 columns]

Forwards by custom categories: now_cost
budget      30
mid-tier    16
fodder      12
top-tier     8
premium      2
Name: count, dtype: int64

'Forwards Prices:'

    now_cost                 name team fpl_pos  defcon price_category
0        155       Erling Haaland  MCI     FWD     NaN        premium
1         90       Alexander Isak  LIV     FWD     NaN        premium
2         80        Ollie Watkins  AVL     FWD     NaN       top-tier
3         80               Thiago  BRE     FWD     NaN       top-tier
4         75         Hugo Ekitike  LIV     FWD     NaN       top-tier
..       ...                  ...  ...     ...     ...            ...
63        45   Sindre Walle Egeli  IPS     FWD     NaN         fodder
64        45        Mason Burstow  HUL     FWD     NaN         fodder
65        45  Chidozie Obi-Martin  MUN     FWD     NaN         fodder
66        45           Sean Neave  NEW     FWD     NaN         fodder
67        45        Dane Scarlett  TOT     FWD     NaN         fodder

[68 rows x 6 columns]

Goalkeepers by custom categories: now_cost
budget      24
fodder      20
mid-tier    14
premium      4
Name: count, dtype: int64

'Goalkeepers Prices:'

    now_cost                  name team fpl_pos  defcon price_category
0         60            David Raya  ARS     GKP     NaN        premium
1         55       Jordan Pickford  EVE     GKP     NaN        premium
2         55  Gianluigi Donnarumma  MCI     GKP     NaN        premium
3         55               Alisson  LIV     GKP     NaN        premium
4         50         Illan Meslier  ARS     GKP     NaN       mid-tier
..       ...                   ...  ...     ...     ...            ...
57        40       Vitezslav Jaros  LIV     GKP     NaN         fodder
58        40            Tom Heaton  MUN     GKP     NaN         fodder
59        40        Brandon Austin  TOT     GKP     NaN         fodder
60        40       Martin Dúbravka  TOT     GKP     NaN         fodder
61        40     Anthony Patterson  SUN     GKP     NaN         fodder

[62 rows x 6 columns]

In [99]:
players_df = pd.concat([mids_df, defs_df, fwds_df, gks_df], ignore_index=True)
display(f"All Players Prices:",  players_df.sort_values("now_cost", ascending=False).reset_index(drop=True))

'All Players Prices:'

     now_cost               name team fpl_pos  defcon price_category
0         155     Erling Haaland  MCI     FWD     NaN        premium
1         120    Bruno Fernandes  MUN     MID     NaN        premium
2          95        Bukayo Saka  ARS     MID     NaN        premium
3          95        Cole Palmer  CHE     MID     NaN        premium
4          90     Alexander Isak  LIV     FWD     NaN        premium
..        ...                ...  ...     ...     ...            ...
559        40     Arthur Masuaku  SUN     DEF     NaN         fodder
560        40         Tom Heaton  MUN     GKP     NaN         fodder
561        40     Brandon Austin  TOT     GKP     NaN         fodder
562        40    Martin Dúbravka  TOT     GKP     NaN         fodder
563        40  Anthony Patterson  SUN     GKP     NaN         fodder

[564 rows x 6 columns]

In [ ]:
#players 90s and points/90
#mids
mids_df = players_defcon_df[players_defcon_df['fpl_pos'].eq('MID')].sort_values("defcon", ascending=False).reset_index(drop=True)
mids_df = mids_df[mids_df['minutes'] > 900]

#per 90s calculations
mids_df['90s'] = mids_df['minutes'] / 90
mids_df['ppg'] = mids_df['total_points'] / mids_df['90s']
mids_df['ppg'] = mids_df['ppg'].round(2)
mids_df['goals_per_90'] = mids_df['goals_scored'] / mids_df['90s']
mids_df['assists_per_90'] = mids_df['assists'] / mids_df['90s']
mids_df['defcon_90s'] = mids_df['defcon'] / mids_df['90s']
mids_df['cs_90s'] = mids_df['clean_sheets'] / mids_df['90s']
mids_df['yc_90s'] = mids_df['yellow_cards'] / mids_df['90s']
mids_df['rc_90s'] = mids_df['red_cards'] / mids_df['90s']


#points calculations
mids_df['gPts'] = mids_df['goals_per_90'] * 5
mids_df['aPts'] = mids_df['assists_per_90'] * 3
mids_df['dcPts'] = (mids_df['defcon_90s'] / 12) * 2
mids_df['csPts'] = mids_df['cs_90s'] * 1
mids_df['ycPts'] = mids_df['yc_90s'] * -1
mids_df['rcPts'] = mids_df['rc_90s'] * -3




min_pts = mids_df['ppg'].min()
max_pts = mids_df['ppg'].max()
display(f"Midfielders points/90:",  mids_df.sort_values("goals_per_90", ascending=False).reset_index(drop=True))
print(f"Midfielders - Min points/90: {min_pts}, Max points/90: {max_pts}")

#defs
defs_df = players_defcon_df[players_defcon_df['fpl_pos'].eq('DEF')].sort_values("defcon", ascending=False).reset_index(drop=True)
defs_df = defs_df[defs_df['minutes'] > 900]
defs_df['90s'] = defs_df['minutes'] / 90
defs_df['ppg'] = defs_df['total_points'] / defs_df['90s']
defs_df['ppg'] = defs_df['ppg'].round(2)
defs_df['goals_per_90'] = defs_df['goals_scored'] / defs_df['90s']
defs_df['assists_per_90'] = defs_df['assists'] / defs_df['90s']
defs_df['defcon_90s'] = defs_df['defcon'] / defs_df['90s']
defs_df['cs_90s'] = defs_df['clean_sheets'] / defs_df['90s']
defs_df['gc_90s'] = defs_df['goals_conceded'] / defs_df['90s']
defs_df['yc_90s'] = defs_df['yellow_cards'] / defs_df['90s']
defs_df['rc_90s'] = defs_df['red_cards'] / defs_df['90s']
min_pts = defs_df['ppg'].min()
max_pts = defs_df['ppg'].max()
display(f"Defenders points/90:",  defs_df.sort_values("ppg", ascending=False).reset_index(drop=True))
print(f"Defenders - Min points/90: {min_pts}, Max points/90: {max_pts}")

#fwds
fwds_df = players_defcon_df[players_defcon_df['fpl_pos'].eq('FWD')].sort_values("defcon", ascending=False).reset_index(drop=True)
fwds_df = fwds_df[fwds_df['minutes'] > 900]
fwds_df['90s'] = fwds_df['minutes'] / 90
fwds_df['ppg'] = fwds_df['total_points'] / fwds_df['90s']
fwds_df['ppg'] = fwds_df['ppg'].round(2)
fwds_df['goals_per_90'] = fwds_df['goals_scored'] / fwds_df['90s']
fwds_df['assists_per_90'] = fwds_df['assists'] / fwds_df['90s']
fwds_df['defcon_90s'] = fwds_df['defcon'] / fwds_df['90s']
fwds_df['yc_90s'] = fwds_df['yellow_cards'] / fwds_df['90s']
fwds_df['rc_90s'] = fwds_df['red_cards'] / fwds_df['90s']
min_pts = fwds_df['ppg'].min()
max_pts = fwds_df['ppg'].max()  
display(f"Forwards points/90:",  fwds_df.sort_values("ppg", ascending=False).reset_index(drop=True))
print(f"Forwards - Min points/90: {min_pts}, Max points/90: {max_pts}")

#gks
gks_df = players_defcon_df[players_defcon_df['fpl_pos'].eq('GKP')].sort_values("defcon", ascending=False).reset_index(drop=True)
gks_df = gks_df[gks_df['minutes'] > 900]
gks_df['90s'] = gks_df['minutes'] / 90
gks_df['ppg'] = gks_df['total_points'] / gks_df['90s']
gks_df['ppg'] = gks_df['ppg'].round(2)
gks_df['saves_per_90'] = gks_df['saves'] / gks_df['90s']
gks_df['gc_per_90'] = gks_df['goals_conceded'] / gks_df['90s']
min_pts = gks_df['ppg'].min()
max_pts = gks_df['ppg'].max()
display(f"Goalkeepers points/90:",  gks_df.sort_values("ppg", ascending=False).reset_index(drop=True))
print(f"Goalkeepers - Min points/90: {min_pts}, Max points/90: {max_pts}")

'Midfielders points/90:'

,goals_scored,assists,total_points,minutes,goals_conceded,bonus,bps,clean_sheets,red_cards,yellow_cards,now_cost,name,team,fpl_pos,defcon,saves,penalties_saved,penalties_missed,90s,ppg,goals_per_90,assists_per_90,defcon_90s,cs_90s,yc_90s,rc_90s,gPts,aPts,dcPts,csPts,ycPts,rcPts
0,17,6,202,3200,52,18,678,12,0,7,80,Antoine Semenyo,MCI,MID,277.0,NaN,NaN,NaN,35.555556,5.68,0.478125,0.168750,7.790625,0.337500,0.196875,0.0,2.390625,0.506250,1.298437,0.337500,-0.196875,-0.0
1,8,3,109,1553,26,11,354,6,0,3,55,Noah Okafor,LEE,MID,112.0,NaN,NaN,NaN,17.255556,6.32,0.463619,0.173857,6.490663,0.347714,0.173857,0.0,2.318094,0.521571,1.081777,0.347714,-0.173857,-0.0
2,10,2,114,1954,33,11,430,3,0,5,103,Cole Palmer,CHE,MID,133.0,NaN,NaN,NaN,21.711111,5.25,0.460594,0.092119,6.125896,0.138178,0.230297,0.0,2.302968,0.276356,1.020983,0.138178,-0.230297,-0.0
3,15,4,188,3101,45,18,712,10,0,1,76,Morgan Gibbs-White,NFO,MID,197.0,NaN,NaN,NaN,34.455556,5.46,0.435343,0.116092,5.717510,0.290229,0.029023,0.0,2.176717,0.348275,0.952918,0.290229,-0.029023,-0.0
4,5,2,67,1110,10,3,238,6,0,1,54,Rayan,BOU,MID,94.0,NaN,NaN,NaN,12.333333,5.43,0.405405,0.162162,7.621622,0.486486,0.081081,0.0,2.027027,0.486486,1.270270,0.486486,-0.081081,-0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,0,1,40,1092,27,0,248,2,0,1,56,James Ward-Prowse,BUR,MID,102.0,NaN,NaN,NaN,12.133333,3.30,0.000000,0.082418,8.406593,0.164835,0.082418,0.0,0.000000,0.247253,1.401099,0.164835,-0.082418,-0.0
149,0,2,42,1030,13,0,182,4,0,1,51,Oscar Bobb,FUL,MID,85.0,NaN,NaN,NaN,11.444444,3.67,0.000000,0.174757,7.427184,0.349515,0.087379,0.0,0.000000,0.524272,1.237864,0.349515,-0.087379,-0.0
150,0,2,46,972,13,6,176,2,0,0,53,Wilson Odobert,TOT,MID,86.0,NaN,NaN,NaN,10.800000,4.26,0.000000,0.185185,7.962963,0.185185,0.000000,0.0,0.000000,0.555556,1.327160,0.185185,-0.000000,-0.0
151,0,1,48,1302,28,0,179,2,0,0,65,Anthony Elanga,NEW,MID,62.0,NaN,NaN,NaN,14.466667,3.32,0.000000,0.069124,4.285714,0.138249,0.000000,0.0,0.000000,0.207373,0.714286,0.138249,-0.000000,-0.0
152,0,1,41,1014,29,0,123,3,0,0,52,Jacob Bruun Larsen,BUR,MID,65.0,NaN,NaN,NaN,11.266667,3.64,0.000000,0.088757,5.769231,0.266272,0.000000,0.0,0.000000,0.266272,0.961538,0.266272,-0.000000,-0.0

Midfielders - Min points/90: 2.49, Max points/90: 6.9

'Defenders points/90:'

,goals_scored,assists,total_points,minutes,goals_conceded,bonus,bps,clean_sheets,red_cards,yellow_cards,now_cost,name,team,fpl_pos,defcon,saves,penalties_saved,penalties_missed,90s,ppg,goals_per_90,assists_per_90,defcon_90s,cs_90s,gc_90s,yc_90s,rc_90s
0,3,5,209,2750,20,30,724,18,0,4,73,Gabriel Magalhães,ARS,DEF,242.0,NaN,NaN,NaN,30.555556,6.84,0.098182,0.163636,7.920000,0.589091,0.654545,0.130909,0.000000
1,4,4,95,1440,20,11,321,4,0,5,41,Patrick Dorgu,MUN,DEF,105.0,NaN,NaN,NaN,16.000000,5.94,0.250000,0.250000,6.562500,0.250000,1.250000,0.312500,0.000000
2,1,2,109,1697,8,6,389,13,0,5,56,Riccardo Calafiori,ARS,DEF,98.0,NaN,NaN,NaN,18.855556,5.78,0.053035,0.106070,5.197407,0.689452,0.424278,0.265174,0.000000
3,0,2,60,971,8,9,237,5,0,2,57,Rayan Aït-Nouri,MCI,DEF,65.0,NaN,NaN,NaN,10.788889,5.56,0.000000,0.185376,6.024717,0.463440,0.741504,0.185376,0.000000
4,0,5,63,1032,13,1,237,5,0,1,57,Jeremie Frimpong,LIV,DEF,51.0,NaN,NaN,NaN,11.466667,5.49,0.000000,0.436047,4.447674,0.436047,1.133721,0.087209,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,0,2,70,3095,66,3,242,4,0,9,44,Kyle Walker,BUR,DEF,225.0,NaN,NaN,NaN,34.388889,2.04,0.000000,0.058158,6.542811,0.116317,1.919225,0.261712,0.000000
124,0,1,29,1335,25,1,121,1,0,4,43,Destiny Udogie,TOT,DEF,66.0,NaN,NaN,NaN,14.833333,1.96,0.000000,0.067416,4.449438,0.067416,1.685393,0.269663,0.000000
125,0,0,23,1100,29,0,86,0,1,1,42,Emmanuel Agbadou,WOL,DEF,106.0,NaN,NaN,NaN,12.222222,1.88,0.000000,0.000000,8.672727,0.000000,2.372727,0.081818,0.081818
126,0,0,25,1405,30,0,127,1,1,1,38,Lucas,BUR,DEF,106.0,NaN,NaN,NaN,15.611111,1.60,0.000000,0.000000,6.790036,0.064057,1.921708,0.064057,0.064057
127,0,0,19,1139,27,0,93,0,0,7,46,Jorrel Hato,CHE,DEF,100.0,NaN,NaN,NaN,12.655556,1.50,0.000000,0.000000,7.901668,0.000000,2.133450,0.553117,0.000000

Defenders - Min points/90: 1.5, Max points/90: 6.84

'Forwards points/90:'

,goals_scored,assists,total_points,minutes,goals_conceded,bonus,bps,clean_sheets,red_cards,yellow_cards,now_cost,name,team,fpl_pos,defcon,saves,penalties_saved,penalties_missed,90s,ppg,goals_per_90,assists_per_90,defcon_90s,yc_90s,rc_90s
0,27,8,239,2953,32,43,952,13,0,2,147,Erling Haaland,MCI,FWD,100.0,NaN,NaN,NaN,32.811111,7.28,0.822892,0.243820,3.047748,0.060955,0.0
1,11,4,125,1797,25,22,433,7,0,0,90,Hugo Ekitike,LIV,FWD,88.0,NaN,NaN,NaN,19.966667,6.26,0.550918,0.200334,4.407346,0.000000,0.0
2,6,1,73,1065,23,8,268,3,0,0,50,Lukas Nmecha,LEE,FWD,67.0,NaN,NaN,NaN,11.833333,6.17,0.507042,0.084507,5.661972,0.000000,0.0
3,11,2,111,1630,30,19,405,2,0,2,72,Benjamin Šeško,MUN,FWD,71.0,NaN,NaN,NaN,18.111111,6.13,0.607362,0.110429,3.920245,0.110429,0.0
4,13,0,113,1663,21,13,480,10,0,5,47,Eli Junior Kroupi,BOU,FWD,120.0,NaN,NaN,NaN,18.477778,6.12,0.703548,0.000000,6.494287,0.270595,0.0
5,9,1,104,1551,19,15,343,5,0,3,51,Beto,EVE,FWD,94.0,NaN,NaN,NaN,17.233333,6.03,0.522244,0.058027,5.454545,0.174081,0.0
6,15,9,177,2658,36,30,715,10,0,5,74,João Pedro,CHE,FWD,136.0,NaN,NaN,NaN,29.533333,5.99,0.507901,0.304740,4.604966,0.169300,0.0
7,7,2,80,1234,24,7,296,1,0,1,58,Callum Wilson,WHU,FWD,42.0,NaN,NaN,NaN,13.711111,5.83,0.510535,0.145867,3.063209,0.072934,0.0
8,6,1,74,1148,17,7,266,4,0,1,50,Wilson Isidor,SUN,FWD,53.0,NaN,NaN,NaN,12.755556,5.80,0.470383,0.078397,4.155052,0.078397,0.0
9,11,4,119,1954,27,17,505,7,0,5,65,Richarlison,TOT,FWD,145.0,NaN,NaN,NaN,21.711111,5.48,0.506653,0.184237,6.678608,0.230297,0.0
10,16,4,167,2833,38,26,623,9,0,4,87,Ollie Watkins,AVL,FWD,95.0,NaN,NaN,NaN,31.477778,5.31,0.508295,0.127074,3.018002,0.127074,0.0
11,14,1,128,2217,14,16,474,12,0,5,91,Viktor Gyökeres,ARS,FWD,89.0,NaN,NaN,NaN,24.633333,5.20,0.568336,0.040595,3.612991,0.202977,0.0
12,8,4,108,1896,29,12,399,8,0,0,67,Nick Woltemade,NEW,FWD,98.0,NaN,NaN,NaN,21.066667,5.13,0.379747,0.189873,4.651899,0.000000,0.0
13,11,0,99,1764,35,11,371,3,0,5,53,Zian Flemming,BUR,FWD,96.0,NaN,NaN,NaN,19.600000,5.05,0.561224,0.000000,4.897959,0.255102,0.0
14,13,1,126,2249,28,18,511,10,0,5,63,Danny Welbeck,BHA,FWD,120.0,NaN,NaN,NaN,24.988889,5.04,0.520231,0.040018,4.802134,0.200089,0.0
15,22,1,181,3282,50,22,710,10,0,7,72,Thiago,BRE,FWD,214.0,NaN,NaN,NaN,36.466667,4.96,0.603291,0.027422,5.868373,0.191956,0.0
16,9,13,187,3406,63,28,731,8,0,4,78,Jarrod Bowen,WHU,FWD,280.0,NaN,NaN,NaN,37.844444,4.94,0.237816,0.343511,7.398708,0.105696,0.0
17,14,2,142,2721,34,20,472,8,0,3,58,Dominic Calvert-Lewin,LEE,FWD,97.0,NaN,NaN,NaN,30.233333,4.70,0.463065,0.066152,3.208379,0.099228,0.0
18,12,0,114,2210,29,13,397,8,0,2,76,Jean-Philippe Mateta,CRY,FWD,124.0,NaN,NaN,NaN,24.555556,4.64,0.488688,0.000000,5.049774,0.081448,0.0
19,9,5,112,2183,28,7,410,9,0,5,59,Raúl Jiménez,FUL,FWD,127.0,NaN,NaN,NaN,24.255556,4.62,0.371049,0.206138,5.235914,0.206138,0.0
20,8,0,95,1898,34,9,295,7,0,3,57,Thierno Barry,EVE,FWD,78.0,NaN,NaN,NaN,21.088889,4.50,0.379347,0.000000,3.698630,0.142255,0.0
21,6,6,114,2293,37,13,407,9,0,2,59,Igor Jesus,NFO,FWD,119.0,NaN,NaN,NaN,25.477778,4.47,0.235499,0.235499,4.670737,0.078500,0.0
22,7,2,92,1920,30,12,309,6,0,6,53,Brian Brobbey,SUN,FWD,76.0,NaN,NaN,NaN,21.333333,4.31,0.328125,0.093750,3.562500,0.281250,0.0
23,3,2,66,1402,28,4,221,3,0,1,51,Tolu Arokodare,WOL,FWD,89.0,NaN,NaN,NaN,15.577778,4.24,0.192582,0.128388,5.713267,0.064194,0.0
24,6,1,61,1384,16,5,243,9,0,6,55,Valentín Castellanos,WHU,FWD,75.0,NaN,NaN,NaN,15.377778,3.97,0.390173,0.065029,4.877168,0.390173,0.0
25,3,2,58,1361,30,4,202,4,0,4,49,Lyle Foster,BUR,FWD,85.0,NaN,NaN,NaN,15.122222,3.84,0.198384,0.132256,5.620867,0.264511,0.0
26,6,7,115,2741,40,6,412,11,0,2,66,Evanilson,BOU,FWD,139.0,NaN,NaN,NaN,30.455556,3.78,0.197008,0.229843,4.564028,0.065669,0.0
27,3,2,74,1787,30,9,314,5,0,0,42,Mateus Mane,WOL,FWD,142.0,NaN,NaN,NaN,19.855556,3.73,0.151091,0.100727,7.151651,0.000000,0.0
28,1,2,45,1092,18,1,123,2,0,4,62,Liam Delap,CHE,FWD,45.0,NaN,NaN,NaN,12.133333,3.71,0.082418,0.164835,3.708791,0.329670,0.0
29,3,0,40,997,21,4,187,0,0,1,71,Dominic Solanke,TOT,FWD,70.0,NaN,NaN,NaN,11.077778,3.61,0.270812,0.000000,6.318957,0.090271,0.0
30,1,1,36,987,13,3,94,3,0,2,53,Rodrigo Muniz,FUL,FWD,49.0,NaN,NaN,NaN,10.966667,3.28,0.091185,0.091185,4.468085,0.182371,0.0
31,2,2,39,1141,20,1,129,3,0,3,51,Adam Armstrong,WOL,FWD,39.0,NaN,NaN,NaN,12.677778,3.08,0.157756,0.157756,3.076249,0.236635,0.0
32,4,1,75,2301,41,3,215,5,0,4,58,Jørgen Strand Larsen,CRY,FWD,99.0,NaN,NaN,NaN,25.566667,2.93,0.156454,0.039113,3.872229,0.156454,0.0
33,1,1,52,1655,31,1,150,4,0,3,69,Randal Kolo Muani,TOT,FWD,114.0,NaN,NaN,NaN,18.388889,2.83,0.054381,0.054381,6.199396,0.163142,0.0

Forwards - Min points/90: 2.83, Max points/90: 7.28

'Goalkeepers points/90:'

,goals_scored,assists,total_points,minutes,goals_conceded,bonus,bps,clean_sheets,red_cards,yellow_cards,now_cost,name,team,fpl_pos,defcon,saves,penalties_saved,penalties_missed,90s,ppg,saves_per_90,gc_per_90
0,0,0,162,3330,26,11,633,19,0,1,62,David Raya,ARS,GKP,30.0,60.0,NaN,NaN,37.000000,4.38,1.621622,0.702703
1,0,1,76,1620,28,8,282,7,0,0,42,Mads Hermansen,WHU,GKP,8.0,57.0,NaN,NaN,18.000000,4.22,3.166667,1.555556
2,0,0,135,3060,29,5,567,15,0,8,56,Gianluigi Donnarumma,MCI,GKP,17.0,81.0,NaN,NaN,34.000000,3.97,2.382353,0.852941
3,0,0,136,3150,46,12,573,10,0,4,48,Robin Roefs,SUN,GKP,12.0,110.0,NaN,NaN,35.000000,3.89,3.142857,1.314286
4,0,0,143,3330,49,11,570,10,0,1,48,Caoimhín Kelleher,BRE,GKP,17.0,110.0,NaN,NaN,37.000000,3.86,2.972973,1.324324
5,0,1,120,2835,39,11,530,7,0,2,50,Emiliano Martínez,AVL,GKP,17.0,95.0,NaN,NaN,31.500000,3.81,3.015873,1.238095
6,0,1,96,2416,38,3,414,7,0,2,50,Nick Pope,NEW,GKP,24.0,89.0,NaN,NaN,26.844444,3.58,3.315397,1.415563
7,0,0,135,3420,50,11,545,11,0,4,56,Jordan Pickford,EVE,GKP,35.0,100.0,NaN,NaN,38.000000,3.55,2.631579,1.315789
8,0,0,131,3330,51,7,538,11,0,5,51,Dean Henderson,CRY,GKP,22.0,106.0,NaN,NaN,37.000000,3.54,2.864865,1.378378
9,0,0,105,2667,39,3,431,7,0,2,46,Matz Sels,NFO,GKP,15.0,95.0,NaN,NaN,29.633333,3.54,3.205849,1.316085
10,0,0,91,2340,31,8,389,8,0,1,54,Alisson,LIV,GKP,16.0,57.0,NaN,NaN,26.000000,3.50,2.192308,1.192308
11,0,0,130,3420,46,6,616,10,0,3,46,Bart Verbruggen,BHA,GKP,18.0,107.0,NaN,NaN,38.000000,3.42,2.815789,1.210526
12,0,0,109,2880,39,11,413,8,0,0,51,Senne Lammens,MUN,GKP,13.0,80.0,NaN,NaN,32.000000,3.41,2.500000,1.218750
13,0,1,113,3040,49,7,509,9,1,3,48,Robert Sánchez,CHE,GKP,20.0,102.0,NaN,NaN,33.777778,3.35,3.019737,1.450658
14,0,0,124,3420,54,5,512,11,0,3,46,Đorđe Petrović,BOU,GKP,27.0,110.0,NaN,NaN,38.000000,3.26,2.894737,1.421053
15,0,0,71,1980,27,3,334,5,0,1,40,Karl Darlow,LEE,GKP,13.0,63.0,NaN,NaN,22.000000,3.23,2.863636,1.227273
16,0,0,122,3420,51,8,556,9,0,3,50,Bernd Leno,FUL,GKP,18.0,98.0,NaN,NaN,38.000000,3.21,2.578947,1.342105
17,0,0,68,2070,37,8,303,4,0,2,42,José Sá,WOL,GKP,18.0,65.0,NaN,NaN,23.000000,2.96,2.826087,1.608696
18,0,0,90,2790,50,6,412,7,0,1,47,Guglielmo Vicario,TOT,GKP,20.0,84.0,NaN,NaN,31.000000,2.90,2.709677,1.612903
19,0,0,96,3150,71,7,436,4,0,1,40,Martin Dúbravka,BUR,GKP,18.0,128.0,NaN,NaN,35.000000,2.74,3.657143,2.028571
20,0,0,43,1440,29,3,153,3,0,2,44,Lucas Perri,LEE,GKP,10.0,38.0,NaN,NaN,16.000000,2.69,2.375000,1.812500
21,0,1,51,1800,37,2,220,0,0,0,42,Alphonse Areola,WHU,GKP,9.0,79.0,NaN,NaN,20.000000,2.55,3.950000,1.850000
22,0,0,25,1003,17,1,107,1,0,2,48,Aaron Ramsdale,NEW,GKP,4.0,25.0,NaN,NaN,11.144444,2.24,2.243270,1.525424
23,0,0,21,1080,24,0,117,0,0,0,44,Sam Johnstone,WOL,GKP,11.0,41.0,NaN,NaN,12.000000,1.75,3.416667,2.000000

Goalkeepers - Min points/90: 1.75, Max points/90: 4.38